# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=20)),
                ('gpic', models.ImageField(upload_to='f_goods')),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('isDelete', models.BooleanField(default=False)),
                ('gunit', models.CharField(default='500g', max_length=20)),
                ('gclick', models.ImageField(upload_to=b'')),
                ('gjianjie', models.CharField(max_length=200)),
                ('gstock', models.ImageField(upload_to=b'')),
                ('gcontent', tinymce.models.HTMLField()),
                ('gsales', models.ImageField(upload_to=b'')),
                ('gadv', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='goodinfo',
            name='gtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f_goods.TypeGoods'),
        ),
    ]
