# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_user', '0002_auto_20180612_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='uemail',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
