# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_user', '0003_auto_20180612_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ushou',
            field=models.CharField(default='', max_length=10),
        ),
    ]
